# Generated by Django 4.0.4 on 2022-06-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options_remove_products_is_active_and_more'),
        ('cart', '0011_alter_cart_options_remove_cart_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.products'),
        ),
    ]
