# Generated by Django 4.0.4 on 2022-06-16 12:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_types',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('sales_reps', 'sales_reps')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('Nature_of_buisness', models.CharField(choices=[('b2b_companies', 'b2b_companies'), ('b2c_user', 'b2c_user')], default='b2b_companies', max_length=15)),
                ('Year_of_Establishment', models.DateField()),
                ('product_category', models.CharField(max_length=10)),
                ('revenue', models.DecimalField(decimal_places=3, max_digits=20)),
                ('offline_channel', models.BooleanField()),
                ('company_profile', models.TextField()),
                ('portfolio', models.IntegerField()),
                ('buisness_customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
