# Generated by Django 4.0.4 on 2022-06-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_user_types_buisness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_types',
        ),
    ]
