# Generated by Django 4.0.4 on 2022-06-21 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
