# Generated by Django 4.0.4 on 2022-06-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='parent',
            new_name='manager',
        ),
    ]
