# Generated by Django 4.0.4 on 2022-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_user_products_buisness_user'),
        ('customer', '0008_rename_parent_customer_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buisness',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='buisness_customer',
            new_name='business_customer',
        ),
    ]
