# Generated by Django 4.0.4 on 2022-06-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_buisness_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Nature_of_buisness',
            new_name='Nature_of_business',
        ),
    ]
