# Generated by Django 4.0.4 on 2022-06-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_business_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='business',
            managers=[
            ],
        ),
    ]
