# Generated by Django 4.0.4 on 2022-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_business_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='number_of_employees',
            field=models.IntegerField(default=4),
        ),
    ]
