# Generated by Django 4.0.4 on 2022-06-21 05:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_rename_name_category_categories_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('category', django.db.models.manager.Manager()),
            ],
        ),
    ]
