# Generated by Django 4.0.4 on 2022-07-19 05:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_category_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('name', django.db.models.manager.Manager()),
            ],
        ),
    ]
