# Generated by Django 4.0.4 on 2022-07-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_category_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
