# Generated by Django 4.0.4 on 2022-05-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_sub_category_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('is_bestseller', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('meta_keywords', models.CharField(max_length=50)),
                ('meta_description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('category', models.ManyToManyField(related_name='product', to='category.category')),
            ],
        ),
    ]
