# Generated by Django 4.0.4 on 2022-06-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_user_types'),
        ('products', '0004_alter_products_options_remove_products_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_user', to='customer.buisness'),
        ),
    ]
