# Generated by Django 4.0.4 on 2022-06-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user',
            new_name='buisness_user',
        ),
    ]
