# Generated by Django 4.0.4 on 2022-06-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_user_products_buisness_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='buisness_user',
            new_name='business_user',
        ),
    ]
