# Generated by Django 4.0.4 on 2022-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_area_address_block_address_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
