# Generated by Django 4.0.4 on 2022-06-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cartitem_product'),
        ('order', '0008_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order', to='cart.cart'),
        ),
    ]
