# Generated by Django 4.0.4 on 2022-06-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderhistory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_gained', models.IntegerField(default=0)),
                ('user_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='order.order')),
            ],
        ),
    ]
