# Generated by Django 4.0.4 on 2022-06-13 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_point', to=settings.AUTH_USER_MODEL),
        ),
    ]
