# Generated by Django 4.0.4 on 2022-06-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_points_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
