# Generated by Django 4.0.4 on 2022-06-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='user_point',
        ),
        migrations.AddField(
            model_name='points',
            name='order_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_points', to='order.order'),
        ),
    ]
