# Generated by Django 4.0.4 on 2022-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_address_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_charges',
            field=models.IntegerField(default=0),
        ),
    ]
