# Generated by Django 4.0.4 on 2022-06-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_estimated_delivery_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
