# Generated by Django 4.0.4 on 2022-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
